name: Terraform Variables Debug - MongoDB Atlas

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-debug:
    runs-on: ubuntu-latest
    env:
      TF_VAR_atlas_public_key: ${{ secrets.MONGO_ATLAS_PUBLIC_KEY }}
      TF_VAR_atlas_private_key: ${{ secrets.MONGO_ATLAS_PRIVATE_KEY }}
      TF_VAR_atlas_org_id: ${{ secrets.ORGANIZATION_MONGO_ATLAS_ID }}
      TF_VAR_fastfood_user_password: ${{ secrets.MONGO_DATABASE_ATLAS_FASTFOOD_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Terraform variables
        run: |
          echo "TF_VAR_atlas_public_key = $TF_VAR_atlas_public_key"
          echo "TF_VAR_atlas_private_key = $TF_VAR_atlas_private_key"
          echo "TF_VAR_atlas_org_id = $TF_VAR_atlas_org_id"
          echo "TF_VAR_fastfood_user_password = $TF_VAR_fastfood_user_password"
      - name: List all secrets (for debug)
        run: printenv | grep TF_VAR
