name: Terraform Apply - MongoDB Atlas

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_atlas_public_key: ${{ secrets.MONGO_ATLAS_PUBLIC_KEY }}
      TF_VAR_atlas_private_key: ${{ secrets.MONGO_ATLAS_PRIVATE_KEY }}
      TF_VAR_atlas_org_id: ${{ secrets.ORGANIZATION_MONGO_ATLAS_ID }}
      TF_VAR_fastfood_user_password: ${{ secrets.MONGO_DATABASE_ATLAS_FASTFOOD_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Terraform Outputs
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform output

      - name: Export Terraform Outputs
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: tf-outputs
        run: |
          echo "MONGODB_URI=$(terraform output -raw mongodb_connection_string)" >> $GITHUB_ENV
          echo "MONGODB_USER=$(terraform output -raw mongodb_user)" >> $GITHUB_ENV
          echo "MONGODB_DATABASE=$(terraform output -raw mongodb_database)" >> $GITHUB_ENV

      - name: Install Mongo Shell
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-clients

      - name: Create seed file
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo '${{ secrets.MENU_SEED_JSON }}' > menu.json
          echo "db = connect('$MONGODB_URI');" > seed.js
          echo "db.$MONGODB_DATABASE.insertMany($(cat menu.json));" >> seed.js

      - name: Seed MongoDB
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: mongo "$MONGODB_URI" -u "$MONGODB_USER" -p "${TF_VAR_fastfood_user_password}" --authenticationDatabase "admin" seed.js